package es.uv.uvlive.session;


public enum BusinessError {
    GENERIC_ERROR,
    OK,
    LOGIN_INVALID,
    UNAUTHORIZED,
    SESSION_EXPIRED,
    USER_DEFINED,
    USER_NOT_DEFINED,
    PARAMETERS_INCORRECT,
    CONVERSATION_NOT_EXISTS,
    USER_BLOCKED,
    MERCHANT_NOT_EXISTS,
    ERROR_GETTING_CONVERSATION
}
